### ISSUE TITLE
Issue when using with OFFLINE.Mall ^2.0

### ISSUE THREAD

**Issue by chocolata** [Voilaah/oc-mall-stats#2]
Hi,

Whenever trying to install your plugin in combination with OFFLINE Mall ^v.2.0, I get these issues:

```
PS E:\xxx\xxx\_xampp\htdocs\myproject> php artisan project:sync
Synchronizing Project...
Executing: composer require voilaah/mallstats-plugin --no-update

Using version dev-main for voilaah/mallstats-plugin
./composer.json has been updated
Executing: composer update
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires voilaah/mallstats-plugin dev-main -> satisfiable by voilaah/mallstats-plugin[dev-main].
    - voilaah/mallstats-plugin dev-main requires offline/oc-mall-plugin ^1.1.0 -> found offline/oc-mall-plugin[v1.1.2, ..., v1.x-dev] but it conflicts with your root composer.json require (^2.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

                                                                                                                        
 [ERROR] The command "composer update" failed.

Exit Code: 2(Misuse of shell builtins)

Working directory:
         E:\xxx\xxx\_xampp\htdocs\myproject
```

Could you look into this please? I've been using your plugin in the past and it's really great. Thank you.

**Comment by chrisvidal** [comment]
the plugin is not tested with `Mall 2.0`.

have you tried the composer update with the `--with-all-dependencies` options as mentioned in the error?

**Comment by chocolata** [comment]
Hi Chris,
Thank you for your answer.
I haven't tested that out yet. Wouldn't that cause  a downgrade of the Mall plugin?
Not that much has changed in Mall v2.0, the biggest change being requiring October CMS v2. 
I'm actually using your plugin in combination with Mall v2.0 and it seems to be working fine.
Only when synchronizing or updating, there's an issue and the error below is shown...

Thanks for your feedback.

**Comment by chrisvidal** [comment]
right now, there is a constraints here ` "offline/oc-mall-plugin": "^1.1.0"`
So I would need to test with Mall 2 first before updating this constraint in the plugin

**Comment by chocolata** [comment]
Okay, I understand. No pressure, we'll see it when the update is available. Thank you for your work.

**Comment by chocolata** [comment]
Hi @chrisvidal any word on an update? This is blocking other updates that contain important bugfixes. I've tested it out. The current version of the plugin is completely compatible with Mall v2.

**Comment by chrisvidal** [comment]
[Bump to MALL 2.0](https://github.com/Voilaah/oc-mall-stats/commit/8bd70c354cbc3b0aa4611d58bbe6861f09179f3b)
